### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by RodEsp** [alfaArghya/alfa-leetcode-api#12]
Heya 👋🏼 

I noticed that for the past 3 days I've been getting a `503` error from the API with this message. Is the project still active?
![image](https://github.com/alfaArghya/alfa-leetcode-api/assets/1084688/2b6a67c0-2e3e-48fb-8ddf-333204185773)

**Comment by alfaArghya** [comment]
Yeah, it's still active. Actually Servers free tier is over for the month that's why it was suspended by the server. But now it activate again.

**Comment by RodEsp** [comment]
Awesome, thank you @alfaArghya! <3

P.S. happy to throw a few bucks your way if it helps with hosting costs! 💸
