### ISSUE TITLE
today daily problem i solved or not ?

### ISSUE THREAD

**Issue by sourabCV** [alfaarghya/alfa-leetcode-api#13]
Is there any API that gonna help me to fetch daily problem-related queries like whether is it completed for today or not? or I forgot to attend.

**Comment by alfaarghya** [comment]
this API only gives you daily problems, it doesn't check whether you solved it or not.

but this system can be built by using 2 API endpoints `/daily` & `/:username/acSubmission`

**Comment by sourabCV** [comment]
pls share any python code if you have related to this

**Comment by sourabCV** [comment]
Thank you i completed code☺
