### ISSUE TITLE
FIX : docker-compose for development 

### ISSUE THREAD

**Issue by alfaarghya** [alfaarghya/alfa-leetcode-api#19]
I'm having trouble getting the `docker-compose up` command to work for hot-reload 😅.

To enable hot-reload with `docker-compose up`, we need to modify the `Dockerfile` and `docker-compose.yml`.

#### Can anyone help me fix this problem? 🤔

**Comment by merakesh99** [comment]
version: '3.8'

services:
  app:
    build: .
    container_name: alfa-leetcode-api-docker
    ports:
      - '3000:3000'
    **restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true**
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

**Comment by alfaarghya** [comment]
The issue has been resolved 😀. Thanks for the contribution @merakesh99
