### ISSUE TITLE
Missing endpoints for contests

### ISSUE THREAD

**Issue by chinesedfan** [alfaarghya/alfa-leetcode-api#23]
> '/contest/:contestSlug': 'get contest details',
'/contestRanking/:contestSlug': 'get contest ranking',

Seems like above two endpoints didn't work. Right?

**Comment by alfaarghya** [comment]
Sorry for this inconvenience, the routes are not available! I accidentally wrote those routes in documentation.

**Comment by chinesedfan** [comment]
Solved by https://github.com/alfaarghya/alfa-leetcode-api/commit/f53abd7595517bfb2a5d09a57590b280a9ce23f6.
