### ISSUE TITLE
Regarding Submissions

### ISSUE THREAD

**Issue by Sushant-Gadyal** [alfaarghya/alfa-leetcode-api#26]
When i checked the submissions which is in other format and converted to standard date format , it was showing the data which has still did not occur even. This issue i found in new end point of calender . Please resolve this issue .

**Comment by alfaarghya** [comment]
Please provide a screenshot of it

**Comment by Sushant-Gadyal** [comment]
Hello Sir,
I apologize that it was my mistake where I have written wrong algorithm for
converting those seconds to date
Now i found the correct way of finding the date .
Sorry for distubance

Thank You

**Comment by alfaarghya** [comment]
@Sushant-Gadyal it's fine and no need to apologize!
