### ISSUE TITLE
unable to get the response for selected problem

### ISSUE THREAD

**Issue by ayushg-nitw** [alfaarghya/alfa-leetcode-api#28]
I am unable to find the response from the get request to 

 https://alfa-leetcode-api.vercel.app/select?titleSlug=minimum-cost-to-hire-k-workers 

 or any other titleSlug. It is showing NOT_FOUND error. Please see this and let me know

**Comment by ayushg-nitw** [comment]
working from this api

https://alfa-leetcode-api.onrender.com/select?titleSlug=two-sum

**Comment by alfaarghya** [comment]
@ayushg-nitw as u closed the issue, did u able to find out the problem?

**Comment by ayushg-nitw** [comment]
Acty your vercel.app/select?titleSlug=..
 Is not working as it is giving not found error.

 But
 alfa-leetcode-api.onrender.com/select?titleSlug=.    is  working fine and
giving correct answer.

**Comment by alfaarghya** [comment]
It's because currently I am not using Vercel
