### ISSUE TITLE
Submitting leetcode solution through API

### ISSUE THREAD

**Issue by Manojbhat09** [alfaArghya/alfa-leetcode-api#3]
Is there a way to 
1. Get the problem, 
2. Add your solution
3. Submit on the profile
4. Get stats 

Through the api?

**Comment by alfaArghya** [comment]
1. yes use the `/select` route, in the `titleSlug` query You have to put the question title. For example - the problem title is **Combination Sum II** to get this question you have to put `/select?titleSlug=combination-sum-ii`.

2. No, leetCode doesn't provide that.

3. I don't understand this please explain it.

4.  
<img width="574" alt="image" src="https://github.com/alfaArghya/alfa-leetcode-api/assets/95538110/c288dbc8-c5b0-4331-9616-6e8241777546">

If you want to get this, use - 
+ `/:username/contest` to get contest stats
+ `/:username/solved` to get solved problem stats
+ `/:username/badges` to get badges
+ `/:username/calendar` to get submission calendar

---
