### ISSUE TITLE
Its not fetching user info by username. please check

### ISSUE THREAD

**Issue by technoayan7** [alfaArghya/alfa-leetcode-api#4]
// 20240308170257
// https://alfa-leetcode-api.onrender.com/technoayan

{
  
}

**Comment by technoayan7** [comment]
Thank you sir for your response.

**Comment by makarkananov** [comment]
Experiencing the same issue 😢 
I am also having some troubles trying to work with https://leetcode.com/graphql directly. Probably you have the same problem as me - 403 Forbidden? Anybody knows if it is just Leetcode trouble or we are missing something?

**Comment by alfaArghya** [comment]
@makarkananov Can U please show me a screenshot of the error? 
cuz I am not getting any 403 error while working on https://leetcode.com/graphql 
![image](https://github.com/alfaArghya/alfa-leetcode-api/assets/95538110/bfa163d5-a6d3-449d-a117-fef04f337f60)

**Comment by makarkananov** [comment]
@alfaArghya
My problem was also described here https://www.reddit.com/r/leetcode/comments/18sflv5/leetcode_graphql_endpoint/
![image](https://github.com/alfaArghya/alfa-leetcode-api/assets/52353806/655916cb-530f-4238-850a-28f769489427)

**Comment by alfaArghya** [comment]
@makarkananov  Thanks for the Screenshot. Now I understand the problem.
My API endpoint is not currently working because of that problem 🥲.
But my code is running locally fine. U may use code locally to fetch the problem list  ```http://localhost:3000/problems?limit=100``` & to get details of the problem```http://localhost:3000/select?titleSlug=two-sum```

**Comment by RodEsp** [comment]
FWIW, I run [RodEsp/daily-leetcode-bot](https://github.com/RodEsp/daily-leetcode-bot) and since Wednesday the bot hasn't been able to retrieve the problem of the day from Leetcode's GraphQL query because of the same problem.

When I run the query manually from my PC I get intermittent 403 errors 😞 
![leetcodeapierrors](https://github.com/alfaArghya/alfa-leetcode-api/assets/1084688/4232524a-05ac-4419-baf3-73e15811abbe)

**Comment by alfaArghya** [comment]
@RodEsp yeah!! everyone is facing the same problem. I guess Leetcode changed their policy.

**Comment by RodEsp** [comment]
Hey @alfaArghya, FWIW:

I figured out that for some inexplicable reason requests made using [Python's Requests library](https://docs.python-requests.org/en/latest/index.html) aren't getting blocked by Cloudflare. So I added a python script as a failover to my bot in this commit: https://github.com/RodEsp/daily-leetcode-bot/commit/96ff99976f202548f9b466649e1a7b015f5e019c.

I'm hoping that will fix things for now while I figure out a more elegant (and explicable) solution.

**Comment by alfaArghya** [comment]
@technoayan7 API started working again 🎉, thanks to leetCode team🙏🏽. Now u can fetch data

**Comment by RodEsp** [comment]
@alfaArghya did leetcode post anywhere about this?
I'm still getting blocked on my bot :(

**Comment by RodEsp** [comment]
Sounds good, thanks for the reply :)
FWIW your API is working for me again too.

**Comment by alfaArghya** [comment]
@RodEsp your welcome 🤗
