### ISSUE TITLE
[enhancement] : Give the problem links along with the Response

### ISSUE THREAD

**Issue by Rudrajiii** [alfaarghya/alfa-leetcode-api#43]
This API has 2 endpoints :
- `/problems`
- `/problems?limit=number`
But this endpoints provides all the necessary info except the actual problem link
That's why if someone building some product based on this **API** how can they redirect users
in that exact problem without it's URL??
i have a solution if you would like me to explain then give a response ASAP :)

**Comment by Xtha-Sunil** [comment]
add title slug to base url

**Comment by Rudrajiii** [comment]
@Xtha-Sunil ohh yaa 😅 I am closing this issue then!!

**Comment by Xtha-Sunil** [comment]
no! why? you said this is enhancement; also useful

**Comment by Xtha-Sunil** [comment]
he already did that in /select endpoint. You can add in your mentioned endpoint
![1000101655](https://github.com/user-attachments/assets/507cfe41-a2ed-4393-82b3-b2688e0001d4)
