### ISSUE TITLE
totalSolved count not correct.

### ISSUE THREAD

**Issue by nilesyadv** [alfaarghya/alfa-leetcode-api#45]
Hey I was trying to hit api for my profile to see the stats, and idk how but total problem solved is incorred as response. Rest seems fine to me. 

url: https://alfa-leetcode-api.onrender.com/userProfile/nilesyadv
shows     "totalSolved": 153, but in reality it shoud be around 383.

**Comment by alfaarghya** [comment]
yeah!
I looked into your profile, But I'm not able to find out what's the problem here

**Comment by nilesyadv** [comment]
total solved number looks correct to you?

**Comment by Rudrajiii** [comment]
@alfaarghya does this api giving total numbers of easy , mid and hard problem currently available on leetcode beacuse i checked it but didn't able to find that ;

**Comment by nilesyadv** [comment]
Hi @alfaarghya , here are attachments. 
Total solved as per api call: 153
<img width="368" alt="image" src="https://github.com/user-attachments/assets/8402f997-e319-4067-99d9-7e0a0f2b0bfe">

Total actual solved: 383
<img width="424" alt="image" src="https://github.com/user-attachments/assets/7830143f-b628-4af1-acb7-18de62c7f5f4">

I hope now the problem is clear. Please let me know if you need more details. Thanks for addressing.

**Comment by alfaarghya** [comment]
> yeah!
> I looked into your profile, But I'm not able to find out what's the problem here
> 

I mean it what is the problem with API.

**Comment by alfaarghya** [comment]
> Hi @alfaarghya , here are attachments. 
> Total solved as per api call: 153
> <img width="368" alt="image" src="https://github.com/user-attachments/assets/8402f997-e319-4067-99d9-7e0a0f2b0bfe">
> 
> Total actual solved: 383
> <img width="424" alt="image" src="https://github.com/user-attachments/assets/7830143f-b628-4af1-acb7-18de62c7f5f4">
> 
> I hope now the problem is clear. Please let me know if you need more details. Thanks for addressing. 
> 

 Yeah, it's totally clear to me. Since then I tried with different usernames, and all responses are correct till now.

Sorry for the late response, till yesterday, my exam was going on.

**Comment by nilesyadv** [comment]
Exactly, I also saw it is giving correct numbers with other profiles, but wrong in my case. Anyways, just wanted to bring it to your notice. Can close this issue now. Thanks.

**Comment by nilesyadv** [comment]
Issue was supposed to bring this to @alfaarghya 's notice. Closing now.
