### ISSUE TITLE
Too many requests error

### ISSUE THREAD

**Issue by sahilsh-dev** [alfaArghya/alfa-leetcode-api#8]
When using the api endpoints, I always get 
```
Too many request from this IP, try again in 1 hour
```
even when it is my first request since many hours. This has happened many times. Kindly 
check as to why this is happening. I am sure, I am not making a lot of requests.

**Comment by alfaArghya** [comment]
Okay, I will check it. Meanwhile, try to use it locally. 
And one more thing, can you tell me how you are using it?

**Comment by sahilsh-dev** [comment]
> Okay, I will check it. Meanwhile, try to use it locally. And one more thing, can you tell me how you are using it?

I tried both from browsers and from code with python requests

**Comment by alfaArghya** [comment]
> When using the api endpoints, I always get
> 
> ```
> Too many request from this IP, try again in 1 hour
> ```
> 
> even when it is my first request since many hours. This has happened many times. Kindly check as to why this is happening. I am sure, I am not making a lot of requests.

To be honest, I faced this problem before when I was using the vercel servers. I am not able to figure out what was the problem at that time because locally it works absolutely fine.

**Comment by alfaArghya** [comment]
> > Okay, I will check it. Meanwhile, try to use it locally. And one more thing, can you tell me how you are using it?
> 
> I tried both from browsers and from code with python requests. Got the same response

I will try to figure out what is the problem. 
Meanwhile, try to use it locally with this --> https://github.com/alfaArghya/alfa-leetcode-api/blob/main/CONTRIBUTING.md

**Comment by alfaArghya** [comment]
One more thing: try to use tools like `Postman` to fetch the data. 
In these tools, the response will contain headers where you can find the `ratelimit` key. 
Try this and tell me what it gives in response.

**Comment by sahilsh-dev** [comment]
I haven't tried locally, as I am just looking to use it in a project as api. The issue happens when I try to go to the url after some long time. Then I have to wait for some time for it to work again. I'll close it as I found an alternate. Thanks
