### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by kishan2k2** [alfaArghya/alfa-leetcode-api#9]
I making a web app, a personal project. Can I use this API end point? and What is the rate limit of this API? And is there a way to bypass that? Can you please explain how you made this project happen? I mean the step by step procedure to make this kind of a project happen.

**Comment by kishan2k2** [comment]
Is it using an external source i.e. https://leetcode.com/graphql for collecting the data, do you have your own database?

**Comment by kishan2k2** [comment]
I surfing and I found this answer https://stackoverflow.com/a/74977514/22793103 and this actually got me what I wanted, can you please tell me if there is any kind of rate limit for using this graphQL endpoint?

**Comment by alfaArghya** [comment]
@kishan2k2 
First sorry for this late response.

**Comment by alfaArghya** [comment]
> I making a web app, a personal project. Can I use this API end point? and What is the rate limit of this API? And is there a way to bypass that? Can you please explain how you made this project happen? I mean the step by step procedure to make this kind of a project happen.

The rate-limit is 60 requests/hour. Just remove ```limiter``` variable from the app.ts file to bypass it. But if u want to change the request limit change ```limit``` and to change the time limit change ```windowMs```.

**Comment by alfaArghya** [comment]
> I surfing and I found this answer https://stackoverflow.com/a/74977514/22793103 and this actually got me what I wanted, can you please tell me if there is any kind of rate limit for using this graphQL endpoint?

Till today I don't see any rate limit for the graphQL API

**Comment by kishan2k2** [comment]
Thank you for the response, though I figured it out myself 🤗
